# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: setup/proto/setup.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17setup/proto/setup.proto\x12\x05setup\"k\n\x06System\x12\x15\n\rSRAM_Capacity\x18\n \x01(\x02\x12\x0e\n\x06HBM_BW\x18\x01 \x01(\x02\x12\x14\n\x0cHBM_Capacity\x18\x02 \x01(\x02\x12\x0e\n\x06\x44\x44R_BW\x18\x03 \x01(\x02\x12\x14\n\x0c\x44\x44R_Capacity\x18\x04 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'setup.proto.setup_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYSTEM._serialized_start=34
  _SYSTEM._serialized_end=141
# @@protoc_insertion_point(module_scope)
